import type { FieldConfig } from '@/components/crud/EntityFormModal'

// Table names, keyed by the same short name used across the app/modules.
export const TABLES = {
  users: 'users',
  leads: 'leads',
  opportunities: 'opportunities',
  companies: 'companies',
  contacts: 'contacts',
  sites: 'sites',
  projects: 'projects',
  tasks: 'tasks',
  warehouses: 'warehouses',
  inventoryItems: 'inventory_items',
  stockMovements: 'stock_movements',
  quotes: 'quotes',
  invoices: 'invoices',
  purchaseOrders: 'purchase_orders',
  payments: 'payments',
  evmMetrics: 'evm_metrics',
  surveyReports: 'survey_reports',
  installationRecords: 'installation_records',
  integrationRecords: 'integration_records',
  atpTemplates: 'atp_templates',
  atpRecords: 'atp_records',
  boqs: 'boqs',
  assets: 'assets',
  employees: 'employees',
  vehicles: 'vehicles',
  tools: 'tools',
  purchaseRequests: 'purchase_requests',
  subcontractors: 'subcontractors',
  documents: 'documents',
  contracts: 'contracts',
} as const

const REGIONS = ['Antananarivo', 'Fianarantsoa', 'Toamasina', 'Mahajanga', 'Toliara', 'Antsiranana', 'Antsirabe', 'Morondava']
const TECHS = ['2G', '3G', '4G', '4G+', '5G', 'MW', 'VSAT']

export const FIELD_CONFIGS: Record<string, FieldConfig[]> = {
  leads: [
    { key: 'company', label: 'Company', type: 'select', required: true, lookup: { table: 'companies', valueKey: 'name', labelKey: 'name' } },
    { key: 'contact', label: 'Contact', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'status', label: 'Status', type: 'select', options: ['new', 'contacted', 'qualified', 'unqualified'] },
    { key: 'source', label: 'Source', type: 'select', options: ['referral', 'tender', 'cold_call', 'website', 'partner'] },
    { key: 'value', label: 'Value (Ar)', type: 'number' },
    { key: 'assignedTo', label: 'Assigned To', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  opportunities: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { customerId: 'id' } } },
    { key: 'stage', label: 'Stage', type: 'select', options: ['prospecting', 'proposal', 'negotiation', 'closed_won', 'closed_lost'] },
    { key: 'value', label: 'Value (Ar)', type: 'number' },
    { key: 'probability', label: 'Probability %', type: 'number' },
    { key: 'expectedClose', label: 'Expected Close', type: 'date' },
    { key: 'assignedTo', label: 'Assigned To', type: 'text' },
    { key: 'technologies', label: 'Technologies', type: 'tags', placeholder: '4G, 5G' },
    { key: 'siteCount', label: 'Site Count', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  companies: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: ['telecom_operator', 'tower_company', 'vendor', 'subcontractor', 'government'] },
    { key: 'country', label: 'Country', type: 'text' },
    { key: 'city', label: 'City', type: 'text' },
    { key: 'address', label: 'Address', type: 'text' },
    { key: 'website', label: 'Website', type: 'text' },
    { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
  ],
  contacts: [
    { key: 'companyName', label: 'Company', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { companyId: 'id' } } },
    { key: 'firstName', label: 'First Name', type: 'text', required: true },
    { key: 'lastName', label: 'Last Name', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'isPrimary', label: 'Primary Contact', type: 'checkbox' },
  ],
  sites: [
    { key: 'siteId', label: 'Site ID', type: 'text', required: true, placeholder: 'MDG-TAN-001' },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'region', label: 'Region', type: 'select', options: REGIONS },
    { key: 'latitude', label: 'Latitude', type: 'number' },
    { key: 'longitude', label: 'Longitude', type: 'number' },
    { key: 'technology', label: 'Technology', type: 'tags', placeholder: '4G, 5G' },
    { key: 'status', label: 'Status', type: 'select', options: ['planned', 'survey', 'installation', 'integration', 'atp', 'acceptance', 'live', 'decommissioned'] },
    { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
    { key: 'towerType', label: 'Tower Type', type: 'select', options: ['greenfield', 'rooftop', 'mast', 'shared_tower'] },
    { key: 'powerSource', label: 'Power Source', type: 'select', options: ['grid', 'generator', 'solar', 'hybrid'] },
    { key: 'accessType', label: 'Access Type', type: 'select', options: ['road', 'offroad', 'boat'] },
    { key: 'distanceKm', label: 'Distance (km)', type: 'number' },
    { key: 'revenue', label: 'Revenue (Ar)', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  projects: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'siteId', label: 'Site', type: 'select', lookup: { table: 'sites', valueKey: 'id', labelKey: 'name', labelFormat: '{siteId} — {name}', orderBy: 'siteId' } },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { customerId: 'id' } } },
    { key: 'status', label: 'Status', type: 'select', options: ['not_started', 'in_progress', 'on_hold', 'completed', 'cancelled'] },
    { key: 'currentPhase', label: 'Current Phase', type: 'select', options: ['survey', 'installation', 'integration', 'atp', 'acceptance'] },
    { key: 'startDate', label: 'Start Date', type: 'date' },
    { key: 'endDate', label: 'End Date', type: 'date' },
    { key: 'budget', label: 'Budget (Ar)', type: 'number' },
    { key: 'spent', label: 'Spent (Ar)', type: 'number' },
    { key: 'revenue', label: 'Revenue (Ar)', type: 'number' },
    { key: 'pm', label: 'Project Manager', type: 'text' },
    { key: 'progress', label: 'Progress %', type: 'number' },
    { key: 'region', label: 'Region', type: 'select', options: REGIONS },
  ],
  tasks: [
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'projectName', label: 'Project', type: 'select', lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'status', label: 'Status', type: 'select', options: ['backlog', 'todo', 'in_progress', 'review', 'done'] },
    { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
    { key: 'assigneeName', label: 'Assignee', type: 'text' },
    { key: 'dueDate', label: 'Due Date', type: 'date' },
    { key: 'estimatedHours', label: 'Estimated Hours', type: 'number' },
    { key: 'loggedHours', label: 'Logged Hours', type: 'number' },
    { key: 'phase', label: 'Phase', type: 'select', options: ['survey', 'installation', 'integration', 'atp', 'acceptance'] },
    { key: 'tags', label: 'Tags', type: 'tags' },
  ],
  warehouses: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'city', label: 'City', type: 'text' },
    { key: 'manager', label: 'Manager', type: 'text' },
  ],
  inventory_items: [
    { key: 'sku', label: 'SKU', type: 'text', required: true },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'category', label: 'Category', type: 'select', options: ['antenna', 'radio', 'router', 'cable', 'power_equipment', 'hardware', 'tools', 'transport'] },
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'model', label: 'Model', type: 'text' },
    { key: 'unit', label: 'Unit', type: 'text' },
    { key: 'quantity', label: 'Quantity', type: 'number' },
    { key: 'reserved', label: 'Reserved', type: 'number' },
    { key: 'reorderPoint', label: 'Reorder Point', type: 'number' },
    { key: 'unitCost', label: 'Unit Cost (Ar)', type: 'number' },
    { key: 'warehouseName', label: 'Warehouse', type: 'select', lookup: { table: 'warehouses', valueKey: 'name', labelKey: 'name' } },
    { key: 'location', label: 'Bin/Location', type: 'text' },
    { key: 'serializable', label: 'Serialized items', type: 'checkbox' },
  ],
  stock_movements: [
    { key: 'itemName', label: 'Item', type: 'select', required: true, lookup: { table: 'inventory_items', valueKey: 'name', labelKey: 'name', labelFormat: '{sku} — {name}', orderBy: 'name', populate: { itemId: 'id' } } },
    { key: 'type', label: 'Type', type: 'select', options: ['in', 'out', 'transfer', 'adjustment'] },
    { key: 'quantity', label: 'Quantity', type: 'number', required: true },
    { key: 'fromWarehouse', label: 'From Warehouse', type: 'text' },
    { key: 'toWarehouse', label: 'To Warehouse', type: 'text' },
    { key: 'projectName', label: 'Project', type: 'select', lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'reason', label: 'Reason', type: 'text' },
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'performedBy', label: 'Performed By', type: 'text' },
  ],
  quotes: [
    { key: 'number', label: 'Number', type: 'text', required: true, placeholder: 'QT-2026-001' },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { customerId: 'id' } } },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'sent', 'accepted', 'rejected', 'expired'] },
    { key: 'subtotal', label: 'Subtotal (Ar)', type: 'number' },
    { key: 'taxRate', label: 'Tax Rate %', type: 'number' },
    { key: 'tax', label: 'Tax (Ar)', type: 'number' },
    { key: 'total', label: 'Total (Ar)', type: 'number' },
    { key: 'validUntil', label: 'Valid Until', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  invoices: [
    { key: 'number', label: 'Number', type: 'text', required: true, placeholder: 'INV-2026-001' },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { customerId: 'id' } } },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'sent', 'partially_paid', 'paid', 'overdue', 'cancelled'] },
    { key: 'subtotal', label: 'Subtotal (Ar)', type: 'number' },
    { key: 'taxRate', label: 'Tax Rate %', type: 'number' },
    { key: 'tax', label: 'Tax (Ar)', type: 'number' },
    { key: 'total', label: 'Total (Ar)', type: 'number' },
    { key: 'paid', label: 'Paid (Ar)', type: 'number' },
    { key: 'issueDate', label: 'Issue Date', type: 'date' },
    { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  purchase_orders: [
    { key: 'number', label: 'Number', type: 'text', required: true, placeholder: 'PO-2026-001' },
    { key: 'vendorName', label: 'Vendor', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { vendorId: 'id' } } },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'approved', 'sent', 'partial', 'received', 'cancelled'] },
    { key: 'subtotal', label: 'Subtotal (Ar)', type: 'number' },
    { key: 'tax', label: 'Tax (Ar)', type: 'number' },
    { key: 'total', label: 'Total (Ar)', type: 'number' },
    { key: 'orderDate', label: 'Order Date', type: 'date' },
    { key: 'expectedDelivery', label: 'Expected Delivery', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  payments: [
    { key: 'invoiceNumber', label: 'Invoice #', type: 'text' },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name' } },
    { key: 'amount', label: 'Amount (Ar)', type: 'number', required: true },
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'method', label: 'Method', type: 'select', options: ['bank_transfer', 'mobile_money', 'check', 'cash'] },
    { key: 'reference', label: 'Reference', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  evm_metrics: [
    { key: 'projectName', label: 'Project', type: 'select', required: true, lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name' } },
    { key: 'dataDate', label: 'Data Date', type: 'date' },
    { key: 'bac', label: 'BAC (Ar)', type: 'number' },
    { key: 'pv', label: 'PV (Ar)', type: 'number' },
    { key: 'ev', label: 'EV (Ar)', type: 'number' },
    { key: 'ac', label: 'AC (Ar)', type: 'number' },
    { key: 'percentComplete', label: 'Percent Complete', type: 'number' },
  ],
  survey_reports: [
    { key: 'siteCode', label: 'Site Code', type: 'select', required: true, lookup: { table: 'sites', valueKey: 'siteId', labelKey: 'name', labelFormat: '{siteId} — {name}', orderBy: 'siteId', populate: { siteName: 'name', latitude: 'latitude', longitude: 'longitude', siteId: 'id' } } },
    { key: 'siteName', label: 'Site Name', type: 'text' },
    { key: 'status', label: 'Status', type: 'select', options: ['planned', 'assigned', 'survey_started', 'survey_completed', 'approved'] },
    { key: 'scheduledDate', label: 'Scheduled Date', type: 'date' },
    { key: 'towerType', label: 'Tower Type', type: 'text' },
    { key: 'towerHeight', label: 'Tower Height (m)', type: 'number' },
    { key: 'shelterAvailable', label: 'Shelter Available', type: 'checkbox' },
    { key: 'generatorAvailable', label: 'Generator Available', type: 'checkbox' },
    { key: 'powerSource', label: 'Power Source', type: 'text' },
    { key: 'transmissionType', label: 'Transmission', type: 'select', options: ['fiber', 'mw', 'vsat', 'none'] },
    { key: 'accessibility', label: 'Accessibility', type: 'select', options: ['easy', 'moderate', 'difficult', 'very_difficult'] },
    { key: 'latitude', label: 'Latitude', type: 'number' },
    { key: 'longitude', label: 'Longitude', type: 'number' },
    { key: 'risks', label: 'Risks', type: 'textarea' },
    { key: 'comments', label: 'Comments', type: 'textarea' },
    { key: 'recommendations', label: 'Recommendations', type: 'textarea' },
  ],
  installation_records: [
    { key: 'siteCode', label: 'Site Code', type: 'select', lookup: { table: 'sites', valueKey: 'siteId', labelKey: 'name', labelFormat: '{siteId} — {name}', orderBy: 'siteId', populate: { siteName: 'name', siteId: 'id' } } },
    { key: 'siteName', label: 'Site Name', type: 'text' },
    { key: 'projectName', label: 'Project', type: 'select', lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'status', label: 'Status', type: 'select', options: ['pending', 'material_delivered', 'install_started', 'install_completed', 'quality_check', 'approved'] },
    { key: 'supervisorId', label: 'Supervisor', type: 'text' },
    { key: 'team', label: 'Team', type: 'tags' },
    { key: 'comments', label: 'Comments', type: 'textarea' },
  ],
  integration_records: [
    { key: 'siteCode', label: 'Site Code', type: 'select', lookup: { table: 'sites', valueKey: 'siteId', labelKey: 'name', labelFormat: '{siteId} — {name}', orderBy: 'siteId', populate: { siteName: 'name', siteId: 'id' } } },
    { key: 'siteName', label: 'Site Name', type: 'text' },
    { key: 'projectName', label: 'Project', type: 'select', lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'status', label: 'Status', type: 'select', options: ['pending', 'integration_started', 'testing', 'integrated', 'accepted'] },
    { key: 'engineerId', label: 'Engineer', type: 'text' },
    { key: 'bbuModel', label: 'BBU Model', type: 'text' },
    { key: 'bbuSerial', label: 'BBU Serial', type: 'text' },
    { key: 'ipAddress', label: 'IP Address', type: 'text' },
    { key: 'vlanId', label: 'VLAN ID', type: 'text' },
    { key: 'vswr', label: 'VSWR', type: 'number' },
    { key: 'throughputDL', label: 'Throughput DL', type: 'number' },
    { key: 'throughputUL', label: 'Throughput UL', type: 'number' },
    { key: 'comments', label: 'Comments', type: 'textarea' },
  ],
  atp_templates: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'version', label: 'Version', type: 'text' },
    { key: 'customer', label: 'Customer', type: 'text' },
    { key: 'technologies', label: 'Technologies', type: 'tags' },
    { key: 'isActive', label: 'Active', type: 'checkbox' },
  ],
  atp_records: [
    { key: 'atpNumber', label: 'ATP Number', type: 'text', required: true, placeholder: 'ATP-2026-001' },
    { key: 'siteName', label: 'Site Name', type: 'text' },
    { key: 'siteCode', label: 'Site Code', type: 'text' },
    { key: 'templateName', label: 'Template', type: 'select', lookup: { table: 'atp_templates', valueKey: 'name', labelKey: 'name' } },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'submitted', 'reviewed', 'approved', 'customer_accepted', 'failed'] },
    { key: 'overallResult', label: 'Overall Result', type: 'select', options: ['pass', 'fail', 'partial'] },
    { key: 'engineerName', label: 'Engineer', type: 'text' },
    { key: 'customerRepresentative', label: 'Customer Rep', type: 'text' },
    { key: 'comments', label: 'Comments', type: 'textarea' },
  ],
  boqs: [
    { key: 'boqNumber', label: 'BOQ Number', type: 'text', required: true, placeholder: 'BOQ-2026-001' },
    { key: 'projectName', label: 'Project', type: 'select', lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { customerId: 'id' } } },
    { key: 'siteName', label: 'Site', type: 'text' },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'submitted', 'approved', 'revised', 'superseded'] },
    { key: 'subtotal', label: 'Subtotal (Ar)', type: 'number' },
    { key: 'contingencyPct', label: 'Contingency %', type: 'number' },
    { key: 'grandTotal', label: 'Grand Total (Ar)', type: 'number' },
    { key: 'createdBy', label: 'Created By', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  assets: [
    { key: 'assetTag', label: 'Asset Tag', type: 'text', required: true },
    { key: 'serialNumber', label: 'Serial Number', type: 'text' },
    { key: 'category', label: 'Category', type: 'select', options: ['antenna', 'radio', 'router', 'cable', 'power_equipment', 'hardware', 'tools', 'transport'] },
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'model', label: 'Model', type: 'text' },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'status', label: 'Status', type: 'select', options: ['in_warehouse', 'reserved', 'in_transit', 'on_vehicle', 'on_site', 'installed', 'defective', 'under_repair', 'decommissioned'] },
    { key: 'condition', label: 'Condition', type: 'select', options: ['new', 'good', 'fair', 'poor', 'defective'] },
    { key: 'currentLocation', label: 'Current Location', type: 'text' },
    { key: 'purchaseDate', label: 'Purchase Date', type: 'date' },
    { key: 'purchaseCost', label: 'Purchase Cost (Ar)', type: 'number' },
    { key: 'supplierName', label: 'Supplier', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  employees: [
    { key: 'employeeNumber', label: 'Employee #', type: 'text' },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'role', label: 'Role', type: 'select', options: ['pm', 'supervisor', 'rigger', 'civil_engineer', 'rf_engineer', 'mw_engineer', 'integration_engineer', 'hse_officer', 'driver', 'helper'] },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'skills', label: 'Skills', type: 'tags' },
    { key: 'status', label: 'Status', type: 'select', options: ['available', 'assigned', 'on_leave', 'sick', 'training', 'unavailable'] },
    { key: 'dailyRate', label: 'Daily Rate (Ar)', type: 'number' },
    { key: 'joinedAt', label: 'Joined', type: 'date' },
  ],
  vehicles: [
    { key: 'registration', label: 'Registration', type: 'text', required: true },
    { key: 'make', label: 'Make', type: 'text' },
    { key: 'model', label: 'Model', type: 'text' },
    { key: 'year', label: 'Year', type: 'number' },
    { key: 'type', label: 'Type', type: 'select', options: ['4x4', 'pickup', 'van', 'crane', 'flatbed', 'motorcycle'] },
    { key: 'status', label: 'Status', type: 'select', options: ['available', 'in_use', 'maintenance', 'breakdown'] },
    { key: 'driverName', label: 'Driver', type: 'text' },
    { key: 'currentOdometer', label: 'Odometer (km)', type: 'number' },
    { key: 'fuelType', label: 'Fuel Type', type: 'select', options: ['petrol', 'diesel'] },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  tools: [
    { key: 'toolCode', label: 'Tool Code', type: 'text', required: true },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'category', label: 'Category', type: 'text' },
    { key: 'serialNumber', label: 'Serial Number', type: 'text' },
    { key: 'condition', label: 'Condition', type: 'select', options: ['good', 'fair', 'poor', 'requires_calibration'] },
    { key: 'assignedTo', label: 'Assigned To', type: 'text' },
    { key: 'assignedProject', label: 'Assigned Project', type: 'text' },
    { key: 'nextCalibration', label: 'Next Calibration', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  purchase_requests: [
    { key: 'prNumber', label: 'PR Number', type: 'text', required: true, placeholder: 'PR-2026-001' },
    { key: 'requestedByName', label: 'Requested By', type: 'text' },
    { key: 'projectName', label: 'Project', type: 'select', lookup: { table: 'projects', valueKey: 'name', labelKey: 'name', populate: { projectId: 'id' } } },
    { key: 'urgency', label: 'Urgency', type: 'select', options: ['normal', 'urgent', 'critical'] },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'pending_approval', 'approved', 'rejected', 'po_raised', 'cancelled'] },
    { key: 'totalEstimated', label: 'Total Estimated (Ar)', type: 'number' },
    { key: 'justification', label: 'Justification', type: 'textarea' },
    { key: 'requiredBy', label: 'Required By', type: 'date' },
  ],
  subcontractors: [
    { key: 'companyName', label: 'Company', type: 'select', required: true, lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { companyId: 'id' } } },
    { key: 'contactPerson', label: 'Contact Person', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'specializations', label: 'Specializations', type: 'tags' },
    { key: 'technologies', label: 'Technologies', type: 'tags' },
    { key: 'regions', label: 'Regions', type: 'tags' },
    { key: 'contractValue', label: 'Contract Value (Ar)', type: 'number' },
    { key: 'isApproved', label: 'Approved', type: 'checkbox' },
  ],
  documents: [
    { key: 'docNumber', label: 'Doc Number', type: 'text', required: true },
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: ['contract', 'po', 'atp_report', 'survey_report', 'drawing', 'as_built', 'sow', 'boq', 'invoice', 'nda', 'safety_plan', 'method_statement', 'other'] },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'under_review', 'approved', 'superseded', 'archived'] },
    { key: 'fileUrl', label: 'File URL', type: 'text' },
    { key: 'tags', label: 'Tags', type: 'tags' },
    { key: 'uploadedByName', label: 'Uploaded By', type: 'text' },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'isConfidential', label: 'Confidential', type: 'checkbox' },
  ],
  contracts: [
    { key: 'contractNumber', label: 'Contract Number', type: 'text', required: true },
    { key: 'customerName', label: 'Customer', type: 'select', lookup: { table: 'companies', valueKey: 'name', labelKey: 'name', populate: { customerId: 'id' } } },
    { key: 'type', label: 'Type', type: 'select', options: ['framework', 'project', 'maintenance', 'supply'] },
    { key: 'value', label: 'Value (Ar)', type: 'number' },
    { key: 'startDate', label: 'Start Date', type: 'date' },
    { key: 'endDate', label: 'End Date', type: 'date' },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'completed', 'terminated', 'expired'] },
    { key: 'scopeOfWork', label: 'Scope of Work', type: 'textarea' },
    { key: 'paymentTerms', label: 'Payment Terms', type: 'text' },
    { key: 'retentionPct', label: 'Retention %', type: 'number' },
  ],
  users: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'email', label: 'Email', type: 'text', required: true },
    { key: 'role', label: 'Role', type: 'select', options: ['admin', 'pm', 'engineer', 'finance', 'viewer'] },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
  ],
}

// Guard: every table needs a form config, otherwise its New/Edit modal
// renders blank. Warn loudly instead of letting it fail silently.
for (const t of Object.values(TABLES)) {
  if (!FIELD_CONFIGS[t]) {
    console.warn(`[entityConfigs] Missing FIELD_CONFIGS for table "${t}" — its form will be blank`)
  }
}

export { TECHS, REGIONS }
